### PR TITLE
Update differentiation of inverse trigonometric functions

### PR DESCRIPTION
**Pull request by diluculo**
PR for #41

### CODE REVIEW

**Comment by FoggyFinder** [comment]
@cdrnet please, take a look at this

**Comment by diluculo** [comment]
In the meantime, I found another minor bug: 
`cos(a) * sin(b)` should be `sin(a+b)/2 - sin(a-b)/2`

**Comment by FoggyFinder** [comment]
@diluculo  Where did you find this formula?

**Comment by diluculo** [comment]
@FoggyFinder Angle addition formulas says
(1) `sin(a+b) = sin(a)cos(b) + cos(a)sin(b)`
(2) `sin(a-b) = sin(a)cos(b) - cos(a)sin(b)`
(1) - (2) gives `sin(a+b) - sin(a-b) = 2cos(a)sin(b)`
So, we can get `cos(a)sin(b)= (sin(a+b) - sin(a-b))/2`

Please see [this](https://www.wolframalpha.com/input/?i=cos(a)+sin(b))

**Comment by FoggyFinder** [comment]
@diluculo  oh, right - it seems like I mixed it up with sin(x)*cos(y) 

Do you want add some test?

**Comment by diluculo** [comment]
Some tests for `Trigonometric.contract` are added

**Comment by cdrnet** [comment]
Great, thanks a lot for the fix and the additional tests!

**Pull request merged**
