### PR TITLE
Add missing trigonometric and hyperbolic functions

### PR DESCRIPTION
**Pull request by diluculo**
All missing trigonometric and hyperbolic functions are added.

### CODE REVIEW

**Comment by diluculo** [comment]
In the internet, I couldn't find any reference to express `sinh(n*x)` and `cosh(n*x)` in terms of `sinh(x)` and `cosh(x)` . The picture below shows my formulas used in Trigonometric.expand, very similar to the formulas for [sin(nx) and cos(nx)](http://mathworld.wolfram.com/Multiple-AngleFormulas.html). 

multiple angle formula

**Comment by diluculo** [comment]
In the internet, I couldn't find any reference to express `sinh(n*x)` for positive integer n in terms of `sinh(x)` and `cosh(x)`. The picture below shows my derived formulas that is used in the `Trigonometric.expand`. It is very similar to already implemented `sin(n*x)` in the method.

multiple angle formula

**Comment by cdrnet** [comment]
Indeed - Abramowitz/Stegun does list expansions for n up to 4, but no generic expression either.

Thanks!

**Comment by cdrnet** [comment]
Indeed - Abramowitz/Stegun does list expansions for n up to 4, but no generic expression either.

Thanks!

**Pull request merged**
