### PR TITLE
Added support for more standand functions

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Added support for standard hyperbolic functions `sinh`, `cosh`, `tanh` and for inverse geometric functions `asin`, `acos`, `atan`. Along with `sqrt` as well

### CODE REVIEW

**Comment by cdrnet** [comment]
Great, thanks!

**Comment by cdrnet** [comment]
I wonder whether we should really add `Sqrt` to the `Function` discriminated union. It's great to have the static `Expression.Sqrt` function, the `sqrt` operator and the parser support, we should definitively keep them. But the result should always auto-simplify into a power, and since in Math.NET Symbolics by design expressions are always auto-simplified, there is actually no need to make Sqrt representable.

The same also applies to `Log`.

**Comment by cdrnet** [comment]
Just a thought: maybe there's a need for an intermediate "human readable" expression representation.

**Comment by Zaid-Ajaj** [comment]
I was thinking the same thing, `Sqrt` doesn't need a representation in `Function` as long as the pretty-printer knows how to deal with the powers of different roots. That is to tell the printer that when an expression of the form `Power(x, Expression.One / n)` or `Power (x, Power(n, Expression.MinusOne))` occurs  , to print that as `\sqrt[n] {x}`. One definition could be:

    static member Root(n, x) = Power (x, Power(n, Expression.MinusOne))
    let root n x = Expression.Root (n, x)
and to to used like this:

    root 3 8 // cube root of 8 = 2
The printer will add another case for `Power` like this

    | Power (x, Power(n, Expression.MinusOne)) -> 
        if priority > 3 then write "\\left("
        write "\\sqrt["
        tex write 4 n 
        write "]{"
        tex write 4 x
        write "}"
        if priority > 3 then write "\\right)"
The same goes for `Log`, for a more general definition we could simply define:

    static member Log(b, x) = Expression.Ln(x) / Expression.Ln(b)
    let log b x = Expression.Log(b, x)
and thus removing the code of function application for multiple arguments and complex arguments will be evaluated as expected.

**Comment by cdrnet** [comment]
Finally merged - thanks again!

**Pull request merged**
