### PR TITLE
Update Bessel-type functions

### PR DESCRIPTION
**Pull request by diluculo**
- Upgrade the Numerics to v4.7, supporting the Bessel functions.
- Added BesselIRatio and BesselKRatio.
   - `BesselIRatio(n, x)` is defined as `I(n + 1, x) / I(n, x)`, but calculated with scaled functions to avoid overflow.
   - `BesselKRatio(n, x)` is defined as `K(n + 1, x) / K(n, x)`, but calculated with scaled functions to avoid underflow.
- Added Airy functions `Ai`, `Ai'`, `Bi`, and `Bi'`

@cdrnet, Would you please remove the `MathNet.Symbolics.All.sln`? It contains the `SymbolicsUnitTests` project that has already been removed.

### CODE REVIEW

**Comment by cdrnet** [comment]
Great, thanks! Let me know when I should pull it in.

**Comment by diluculo** [comment]
Finished. Please merge this. Thanks.

**Comment by diluculo** [comment]
I'd like to add the SphericalBessel, Hankel, and Kelvin functions with Gamma function next free time.

**Comment by diluculo** [comment]
@cdrnet, If you didn't apply this yet, I would like to add one more commit: With `Expecto.TestResults`, test result file can be generated.

**Comment by cdrnet** [comment]
Merged, thanks again!

**Pull request merged**
